name: Pipeline

on:
  push:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Start At
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d_%H%M%S')"
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install
        run: npm install
      - name: Linter
        run: npm run lint
      - name: Unit Test
        run: npm run test:unit
      - name: Mutation Test
        run: npm run test:mutate
      - name: Snyk Packages
        run: |
          npx snyk auth ${{ secrets.SNYK_TOKEN }}
          npx snyk monitor --project-name=search-challenge-web
      - name: Snyk Container
        run: |
          npx snyk auth ${{ secrets.SNYK_TOKEN }}
          npm run docker:build
          npx snyk container monitor search-challenger-web:latest --file=Dockerfile --project-name=search-challenge-web
      - name: Login docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            alabra/search-challenge-web:${{ github.run_id }}_${{ steps.date.outputs.date }}
            alabra/search-challenge-web:latest
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'search-challenge-web'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'search-challenge-web:latest'
